version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.0
    container_name: dinet-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 123456
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8081:8080"
    networks:
      - dinet-network
    command: start-dev

networks:
  dinet-network:
    driver: bridge
